-- DEMO_U.T_BOARD definition

CREATE TABLE "T_BOARD" SHARING=METADATA 
   (	"SEQ_NO" NUMBER NOT NULL ENABLE, 
	"USE_YN" VARCHAR2(1) DEFAULT 'Y', 
	"RGST_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"RGST_DT" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"RVSE_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"RVSE_DT" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"TITLE" VARCHAR2(300) ENABLE, 
	"CONT" CLOB, 
	"FILE_ID" VARCHAR2(20), 
	"HTS" NUMBER DEFAULT 0, 
	 CONSTRAINT "T_BOARD_PK" PRIMARY KEY ("SEQ_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SPRING_DEMO"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SPRING_DEMO" 
 LOB ("CONT") STORE AS SECUREFILE (
  TABLESPACE "SPRING_DEMO" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

CREATE UNIQUE INDEX "T_BOARD_PK" ON "T_BOARD" ("SEQ_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SPRING_DEMO" ;
  CREATE UNIQUE INDEX "SYS_IL0000073290C00008$$" ON "T_BOARD" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SPRING_DEMO" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;

COMMENT ON COLUMN DEMO_U.T_BOARD.SERNO IS '일련번호';
COMMENT ON COLUMN DEMO_U.T_BOARD.USE_YN IS '사용 여부';
COMMENT ON COLUMN DEMO_U.T_BOARD.RGST_ID IS '등록자 ID';
COMMENT ON COLUMN DEMO_U.T_BOARD.RGST_DT IS '등록일';
COMMENT ON COLUMN DEMO_U.T_BOARD.RVSE_ID IS '수정자 ID';
COMMENT ON COLUMN DEMO_U.T_BOARD.RVSE_DT IS '수정일';
COMMENT ON COLUMN DEMO_U.T_BOARD.TITLE IS '제목';
COMMENT ON COLUMN DEMO_U.T_BOARD.CONT IS '내용';
COMMENT ON COLUMN DEMO_U.T_BOARD.FILE_ID IS '파일 ID';
COMMENT ON COLUMN DEMO_U.T_BOARD.HTS IS '조회수';