server:
  port: 8000
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: DEMO_U
    password: 12345
    driver-class-name: oracle.jdbc.OracleDriver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo
logging:
  level:
    root: debug